### ISSUE TITLE
how to get image

### ISSUE THREAD

**Issue by Phantom8015** [jozsefsallai/node-craiyon#3]
i dont know how to get image, I am trying to put this into discord bot.

**Comment by jozsefsallai** [comment]
- `res.images` for an array of individual CraiyonImage objects
- `res.asBase64()` for an array of base64-encoded image strings
- `res.asBuffers()` for an array of buffers

the CraiyonImage object has similar methods:

- `image.asBase64()` for the base64-encoded image
- `image.asBuffer()` for a buffer
- `image.stream()` to create a readable stream
- `image.saveToFile('/whatever/path') to save the image to the disk

**Comment by jozsefsallai** [comment]
If you want to generate a grid of images (to send in a Discord message for example), that's out of the scope of this library, so you have to implement it yourself.

Here's an example implementation, you can feel free to take inspiration from it or just copy and paste the whole thing:

- utility wrapper: https://github.com/jozsefsallai/senbot/blob/03699c0592c2232acacc2c8c62b7be6c643666a7/src/utils/craiyon.ts
- generating collage: https://github.com/jozsefsallai/senbot/blob/03699c0592c2232acacc2c8c62b7be6c643666a7/src/utils/collage.ts
- command implementation: https://github.com/jozsefsallai/senbot/blob/03699c0592c2232acacc2c8c62b7be6c643666a7/src/commands/fun/craiyon.ts
